apiVersion: v1
kind: Pod
metadata: 
  name: env-demo
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: conurse
      value: Kubernetes
    - name: trainer
      value: sivakumar