apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: YWRtaW4xMjM0Cg==     # base64 encoded value of "admin"
  password: c2VjdXJl     # base64 encoded value of "secure"
